<a href="https://colab.research.google.com/github/Group-9-AI-ML-class-A/Diabetes-Risk-screener/blob/main/Virtue_Data_Cleaning_CapstoneP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
#Importing Libraries
import pandas as pd
import numpy as np

In [11]:
#Loading the Dataset into a pandas DataFrame called df
df = pd.read_csv('/content/diabetic risk data for grp 9.csv')

In [13]:
#Showing the first 5 rows to understand the Dataset
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [14]:
#Showing the last 5 rows in the Dataset
df.tail()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
14995,14996,47,Male,Mumbai,37.7,No,Sedentary,Non-Vegetarian,Never,Never,6.8,7,213,8.1,150,100,141.7,High,High
14996,14997,48,Female,Mumbai,20.6,No,Moderate,Non-Vegetarian,Never,NaN,6.0,8,162,6.5,132,80,91.0,NaN,Low
14997,14998,34,Female,Nagpur,17.9,No,Active,Vegetarian,Never,Never,7.0,6,137,6.5,136,90,88.8,Low,Low
14998,14999,56,Male,Ahmedabad,20.7,Yes,Active,Vegetarian,Never,Never,6.0,5,163,6.9,140,87,94.8,Low,Low
14999,15000,54,Male,Surat,34.5,No,Moderate,Vegetarian,Never,Never,7.4,2,186,7.2,150,88,130.4,Middle,Moderate

In [62]:
#Checking the size of the Dataset
df.shape

(15000, 19)

In [63]:
#Checking the Data Type
df.dtypes

patient_id                    int64
age                           int64
gender                       object
city                         object
bmi                         float64
family_history_diabetes      object
physical_activity_level      object
diet_type                    object
smoking_status               object
alcohol_consumption          object
hours_sleep_per_night       float64
stress_level                  int64
fasting_blood_sugar           int64
hba1c_level                 float64
blood_pressure_systolic       int64
blood_pressure_diastolic      int64
waist_circumference_cm      float64
income_bracket               object
diabetes_risk                object
dtype: object

In [17]:
#Checking Numerical Variables
df.describe()

,patient_id,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,44.333667,23.062260,7.309860,5.941200,168.789933,6.878387,139.496200,86.256933,100.207933
std,4330.271354,10.383753,4.046391,1.109372,2.148406,38.365822,0.843276,12.660785,8.386529,10.760331
min,1.000000,18.000000,15.000000,3.000000,1.000000,72.000000,4.800000,80.000000,50.000000,73.200000
25%,3750.750000,38.000000,20.100000,6.700000,4.000000,145.000000,6.300000,130.000000,80.000000,92.500000
50%,7500.500000,45.000000,22.700000,7.000000,6.000000,165.000000,6.800000,140.000000,88.000000,99.300000
75%,11250.250000,52.000000,25.600000,8.000000,7.000000,189.000000,7.300000,150.000000,90.000000,106.900000
max,15000.000000,80.000000,40.800000,12.000000,10.000000,400.000000,13.400000,200.000000,120.000000,148.200000

In [18]:
#Checking the DataFrame for missing values
df.isnull()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14996,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False
14997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
#Checking Missing Values
df.isnull().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [64]:
#Giving an Overview of the Dataset, including data types and non_missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                15000 non-null  int64
 1   age                       15000 non-null  int64
 2   gender                    15000 non-null  object
 3   city                      15000 non-null  object
 4   bmi                       15000 non-null  float64
 5   family_history_diabetes   15000 non-null  object
 6   physical_activity_level   15000 non-null  object
 7   diet_type                 15000 non-null  object
 8   smoking_status            15000 non-null  object
 9   alcohol_consumption       15000 non-null  object
 10  hours_sleep_per_night     15000 non-null  float64
 11  stress_level              15000 non-null  int64
 12  fasting_blood_sugar       15000 non-null  int64
 13  hba1c_level               15000 non-null  float64
 14  blood_pressure_systolic   15000 non-null  int64
 15  blood_pressure_diastolic  15000 non-null  int64
 16  waist_circumference_cm    15000 non-null  float64
 17  income_bracket            15000 non-null  object
 18  diabetes_risk             15000 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 2.2+ MB

In [20]:
#Checking Income-bracket
df['income_bracket'].value_counts(dropna=False)

income_bracket
Middle    7305
High      3844
Low       3388
NaN        463
Name: count, dtype: int64

In [21]:
#Mode Calculation for Income-bracket
df['income_bracket'].mode()[0]

'Middle'

In [22]:
#Filling the missing Income values with the Mode
df['income_bracket'] = df['income_bracket'].fillna(df['income_bracket'].mode()[0])

In [23]:
#Counting the number of observations in each income bracket category
df['income_bracket'].value_counts()

income_bracket
Middle    7768
High      3844
Low       3388
Name: count, dtype: int64

In [24]:
#Checking Smoking Status
df['smoking_status'].value_counts(dropna=False)

smoking_status
Never      10119
Current     2946
Former      1463
NaN          472
Name: count, dtype: int64

In [25]:
#Mode Calculation for Smoking Status
df['smoking_status'].mode()[0]

'Never'

In [26]:
#Filling the missing Smoking Status value with the mode
df['smoking_status'] = df['smoking_status'].fillna(df['smoking_status'].mode()[0])

In [27]:
#Counting the number of observations in each Smoking status category
df['smoking_status'].value_counts()

smoking_status
Never      10591
Current     2946
Former      1463
Name: count, dtype: int64

In [28]:
#Checking Alcohol Consumption
df['alcohol_consumption'].value_counts(dropna=False)

alcohol_consumption
Never         5616
Occasional    4483
NaN           3788
Regular       1113
Name: count, dtype: int64

In [33]:
#Mode Calculation for Alcohol Consumption
df['alcohol_consumption'].mode()[0]

'Never'

In [29]:
#Filling the missing Alcohol Consumption values with the mode
df['alcohol_consumption'] = df['alcohol_consumption'].fillna(df['alcohol_consumption'].mode()[0])

In [30]:
#Counting the number of observations in each Alcohol Consumption category
df['alcohol_consumption'].value_counts()

alcohol_consumption
Never         9404
Occasional    4483
Regular       1113
Name: count, dtype: int64

In [54]:
#Summarising Numerical variables for unususally high or low values
df.describe()

,patient_id,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,44.333667,23.062260,7.309860,5.941200,168.789933,6.878387,139.496200,86.256933,100.207933
std,4330.271354,10.383753,4.046391,1.109372,2.148406,38.365822,0.843276,12.660785,8.386529,10.760331
min,1.000000,18.000000,15.000000,3.000000,1.000000,72.000000,4.800000,80.000000,50.000000,73.200000
25%,3750.750000,38.000000,20.100000,6.700000,4.000000,145.000000,6.300000,130.000000,80.000000,92.500000
50%,7500.500000,45.000000,22.700000,7.000000,6.000000,165.000000,6.800000,140.000000,88.000000,99.300000
75%,11250.250000,52.000000,25.600000,8.000000,7.000000,189.000000,7.300000,150.000000,90.000000,106.900000
max,15000.000000,80.000000,40.800000,12.000000,10.000000,400.000000,13.400000,200.000000,120.000000,148.200000

In [59]:
#Reviewing Numerical variables for unusually high or low values
numerical_cols = df.select_dtypes(include=np.number).columns
df[numerical_cols].describe()

,patient_id,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,44.333667,23.062260,7.309860,5.941200,168.789933,6.878387,139.496200,86.256933,100.207933
std,4330.271354,10.383753,4.046391,1.109372,2.148406,38.365822,0.843276,12.660785,8.386529,10.760331
min,1.000000,18.000000,15.000000,3.000000,1.000000,72.000000,4.800000,80.000000,50.000000,73.200000
25%,3750.750000,38.000000,20.100000,6.700000,4.000000,145.000000,6.300000,130.000000,80.000000,92.500000
50%,7500.500000,45.000000,22.700000,7.000000,6.000000,165.000000,6.800000,140.000000,88.000000,99.300000
75%,11250.250000,52.000000,25.600000,8.000000,7.000000,189.000000,7.300000,150.000000,90.000000,106.900000
max,15000.000000,80.000000,40.800000,12.000000,10.000000,400.000000,13.400000,200.000000,120.000000,148.200000

In [60]:
#Checking the distribution of the diabetes risk categories
df['diabetes_risk'].value_counts()

diabetes_risk
Low         9000
Moderate    3750
High        2250
Name: count, dtype: int64

In [34]:
#Final Missing Value Check
df.isnull().sum()

patient_id                  0
age                         0
gender                      0
city                        0
bmi                         0
family_history_diabetes     0
physical_activity_level     0
diet_type                   0
smoking_status              0
alcohol_consumption         0
hours_sleep_per_night       0
stress_level                0
fasting_blood_sugar         0
hba1c_level                 0
blood_pressure_systolic     0
blood_pressure_diastolic    0
waist_circumference_cm      0
income_bracket              0
diabetes_risk               0
dtype: int64

In [36]:
#Checking for Duplicates
df.duplicated().sum()

np.int64(0)